# Select SQL Lab

### Introduction
We've learned all the basics about setting up our SQL database, creating tables, and inserting data. In this lab we will practice querying the data from our salad shop database using `SELECT` statements.

### Setup

In the `src/index.py` file, call the `load_data_to_sql` method to load the data.

Then it's time to query the database.

### Selecting data
Our database is now ready for querying. We will use the python library `sqlite3` for running our SELECT statements.
So to begin, let's select select the employees.

Fill in the appropriate SQL statements inside of each function.

### Select Practice

In the following exercises, answer the question by creating a sql select statement that will provide us with the solution. After reading each question, first create a sql statement, the run it using the cursor object to find the answer. 

> HINT: use the WHERE clause and boolean logic to filter the data within the select statement.


Here's an example:
What ingredients cost less than $1/oz?

In [5]:
import sqlite3

conn = sqlite3.connect('grocery.db')

In [16]:
cursor = conn.cursor()
cursor.execute('SELECT * FROM employees WHERE zip_code IN (10001, 10002);')

In [17]:
cursor.fetchall()

[(1, 'Tom', 'manager', '2019-05-20', 10001, '212-438-3984'),
 (3, 'Jerry', 'delivery driver', '2019-12-15', 10001, '212-219-1029'),
 (4, 'Brian', 'salad maker', '2019-12-04', 10002, '646-328-2309'),
 (6, 'Cindy', 'assistant manager', '2019-11-12', 10002, '212-300-1203'),
 (8, 'Alex', 'assistant manager', '2019-06-11', 10001, '718-293-1823'),
 (9, 'Naomi', 'manager', '2019-02-12', 10002, '212-493-2922'),
 (10, 'Isabel', 'salad maker', '2020-01-04', 10001, '212-390-9122'),
 (12, 'Max', 'salad maker', '2019-10-03', 10002, '212-555-2911')]

In [ ]:
#statement = '''SELECT * FROM ingredients WHERE cost_per_ounce < 1.0'''
#cursor.execute(statement)
#cursor.fetchall()

What date did the employee Naomi begin working? 

Which ingredients expire after February 3rd 2020? 

Which ingredients cost more than 1.00 but less than 1.50?

Which employees' home zip code is 10001 or 10002?

### Conclusion

Using the SELECT statement in sql is how we query the data in the database. We use the SELECT statement to retrieve exactly the data we are interested in analyzing. In this lab we started off with some basic SELECT commands using `SELECT *` to select everything from a table, and `SELECT column_name` to select all the data from a specific column, or columns, in a table.

Most of the time however, we are going to want to add some more complex filters to our SELECT statements, so we can be more precise in the data we are querying. For example, if our employees table had a 1,000,000 rows but we only wanted to see those rows for employees that started after a certain date, we would use a filter to limit the results of a query. The `WHERE` clause is how we filter in our SELECT statements. 

At the end of the lab, we used the `WHERE` clause, in conjunction with boolean logic, to apply filters to the queries.